### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tom95** [jfjlaros/cpp-simple-rpc#6]
Hi! Thank you for the work in this repo. I was wondering whether you intentionally omitted a license or whether it is also supposed to be MIT, like the other simpleRPC repos?

Thank you!

**Comment by jfjlaros** [comment]
This project was never finished, so I did not take the effort to put a license on it.

If you need one, please let me know.

**Comment by tom95** [comment]
Thank you for the swift reply! We would like to use parts of the code as part of an MIT-licensed project, so an MIT license would allow us to include it (and of course credit your work accordingly) :)

**Comment by jfjlaros** [comment]
There you go.

**Comment by tom95** [comment]
Awesome, thanks a lot! And thanks again for the code, as well! :)
